### ISSUE TITLE
TravisCI build sonar-maven-plugin failure due to: Failed to connect to localhost/127.0.0.1:9000: Connection refused (Connection refused)

### ISSUE THREAD

**Issue by vorburger** [KengoTODA/findbugs-slf4j#111]
https://github.com/KengoTODA/findbugs-slf4j/pull/72 just failed like this, but this has nothing to do with that PR (as it did not touch any POM), so this must be some build configuration issue on the current `master` which should be looked into:

```
[INFO] --- sonar-maven-plugin:3.4.1.1168:sonar (default-cli) @ findbugs-slf4j ---
[INFO] User cache: /home/travis/.sonar/cache
[ERROR] SonarQube server [http://localhost:9000] can not be reached
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] findbugs-slf4j ..................................... FAILURE [  2.142 s]
[INFO] findbugs-slf4j bug pattern ......................... SKIPPED
[INFO] findbugs-slf4j test case ........................... SKIPPED
[INFO] findbugs-slf4j sonar plugin ........................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 4.456 s
[INFO] Finished at: 2018-07-23T19:10:59Z
[INFO] Final Memory: 32M/784M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.sonarsource.scanner.maven:sonar-maven-plugin:3.4.1.1168:sonar (default-cli) on project findbugs-slf4j: Unable to execute SonarQube: Fail to get bootstrap index from server: Failed to connect to localhost/127.0.0.1:9000: Connection refused (Connection refused) -> [Help 1]
```

**Comment by vorburger** [comment]
what is a little curious is that https://travis-ci.org/KengoTODA/findbugs-slf4j/builds/407295448 shows it only failed for the build with SLF4J_VERSION=1.7.25, but that's because the `.travis.yml` has this:

    - if [[ $SLF4J_VERSION == "1.7.25" ]]; then ./mvnw sonar:sonar -B; fi

and this (`./mvnw sonar:sonar`) fails locally as well - it seems to expect a Sonar to be locally installed? How can this work on TravisCI?  Or is that what this in `.travis.yml` is for:

```
addons:
  sonarcloud:
    organization: "kengotoda-github"
```

Either way, it seems this is broken.

**Comment by KengoTODA** [comment]
I guess that it was caused because that pull request is external one, that is not supported by this addon:
https://docs.travis-ci.com/user/sonarcloud/

I'll investigate.

**Comment by KengoTODA** [comment]
`$TRAVIS_SECURE_ENV_VARS` seems unset even in internal PR. We need another way to detect internal/external PR.
