### ISSUE TITLE
SLF4J_SIGN_ONLY_FORMAT should not be thrown on usage of throwable

### ISSUE THREAD

**Issue by hazendaz** [KengoTODA/findbugs-slf4j#304]
It is perfectably acceptable to log an exception with slf4j as

logger.error("", e) where e is an throwable exception.

Adding more to that doesn't provide any benefit.  SLF4J will take the exception and print the entire thing.  Added "{}" is flagged by sonarlint and not to be there.  I think this check needs relaxed so it's not thrown to indicate to add more on a throwable it's goign to print.  Is it possible you can check the object it's working with before raising this?  More specifically, if the only reason to throw this is due to lack of anything in the quotes and the only object passwed is a throwable, it really shouldn't be raised.

**Comment by KengoTODA** [comment]
I think this is a kind of policy problem that has no answer. I'll share my thought but it's just my policy.

For me this code `logger.error("", e)` seems strange. It doesn't explain what we expect for person who will read the log. In most cases, I will rethrow `e` to caller side, or use concrete message to motivate reader to take necessary action. This is why the current implementation is designed.
