### ISSUE TITLE
SLF4J_MANUALLY_PROVIDED_MESSAGE should be ignored for TRACE and DEBUG

### ISSUE THREAD

**Issue by melloware** [KengoTODA/findbugs-slf4j#31]
In certain scenarios we want to log a DEBUG of just the localized message and not the full stack trace...

      } catch (BusinessException e) {
         final String localizedMessage = e.getLocalizedMessage();
         LOG.debug("Reporting BusinessException for method {}: {}", new Object[] { methodName, localizedMessage });

We are getting the SLF4J_MANUALLY_PROVIDED_MESSAGE  error.  Maybe that should only be for INFO and higher or WARN and higher?

**Comment by KengoTODA** [comment]
@melloware 
Today I have released version `1.2.0` and it will be deployed onto Maven central soon.
Could you try this version? It should be solution for your case.

* https://github.com/KengoTODA/findbugs-slf4j/releases/tag/findbugs-slf4j-1.2.0

Note that I tested `1.2.0` on Java 8. If your product depends on Java 7 or older one, it might have problem.
