### ISSUE TITLE
Release .jar for Java 6 and 7

### ISSUE THREAD

**Issue by KengoTODA** [KengoTODA/findbugs-slf4j#33]
SLF4J itself supports Java 5+.
To help users, it's better to provide .jar file for Java 5, 6 and 7.

**Comment by jeffjensen** [comment]
Is this because pom's <target> is 1.8?  Can't run with 1.7 since 1.0.11:
"Unsupported major.minor version 52.0"

**Comment by KengoTODA** [comment]
Yes, now this plugin depends on Java8.

**Comment by KengoTODA** [comment]
[Extended support for Java 5.0 is already finished](http://www.oracle.com/technetwork/jp/java/eol-135779.html), so I support only Java 6, 7 and 8.

**Comment by jeffjensen** [comment]
1.2.1 works great with Java 7.  Thank you!
