### ISSUE TITLE
RFE: SLF4J_LOGGER_SHOULD_BE_STATIC

### ISSUE THREAD

**Issue by walles** [KengoTODA/findbugs-slf4j#43]
I'd like to have the opposite rule to `SLF4J_LOGGER_SHOULD_BE_NON_STATIC`, namely `SLF4J_LOGGER_SHOULD_BE_STATIC`.

[The FAQ referred to by this rule](http://www.slf4j.org/faq.html#declared_static) is inconclusive on what people should actually use, but seems to lean slightly towards `static`.

Not sure how to handle having two opposing rules.

**Comment by KengoTODA** [comment]
Thanks for your suggestion.

Currently [we recommend to use default rule provided by PMD](https://github.com/KengoTODA/findbugs-slf4j#slf4j_logger_should_be_non_static) to keep logger static. Can this rule help you?

**Comment by gualtierotesta** [comment]
I agree with @walles that it would be nice to have the "should-be-static" rule in order to enable the right rule accordingly to the project team standards.
PMD and Sonar (Squid rule S1312) prefers static version but this is not a general rule as both of you already mention.

**Comment by KengoTODA** [comment]
I'll close this stale issue.
