### ISSUE TITLE
log4j2 variation

### ISSUE THREAD

**Issue by rdifrango** [KengoTODA/findbugs-slf4j#46]
We are using log4j2 instead of slf4j and given that log4j2 meets the same standards as slf4j, I wonder what the effort would be to port it to support it?

**Comment by KengoTODA** [comment]
Currently I have no plan. And I recommend you to use SLF4J instead of Log4J API directly.

**Comment by rdifrango** [comment]
@KengoTODA That's fair enough.  If its an open source project, I'd agree that SLF4J makes more sense.  In our case, its an internal product and ultimately we've been using LOG4J for 6+ years.

Also, in our performance testing straight LOG4J2 was faster than SLF4J->LOG4J2, hence the choice.

I'm likely going to make a fork of this and attempt to create the LOG4J2 variation.

**Comment by rdifrango** [comment]
@KengoTODA I got it all working except for the `UsingExceptionFromArgumentTest` test.  I'm having a hard time figuring out why that one is failing, is there a specific rule in this plugin that reports this failure that I'm somehow missing?

**Comment by KengoTODA** [comment]
@rdifrango Could you share your topic branch if it's on GitHub? I will check your code.
