### ISSUE TITLE
Gradle example

### ISSUE THREAD

**Issue by punya** [KengoTODA/findbugs-slf4j#48]
I tried to use this plugin in a Gradle build

```gradle
dependencies {
    compile "org.slf4j:slf4j-api:1.7.7"

    findbugsPlugins "jp.skypencil.findbugs.slf4j:findbugs-slf4j:1.2.4"
}
```

but it failed to detect a trivial violation

```java
LOGGER.info("hello " + Math.random());
```

Do you happen to have a working example of using this from Gradle, and if so, could you include it in the README alongside the Maven example? Thanks!

**Comment by punya** [comment]
I figured out that I was trying to use the wrong plugin artifact, but when I tried using `findbugsPlugins "jp.skypencil.findbugs.slf4j:bug-pattern:1.2.4"` instead, I got a `NullPointerException` in `PluginLoader.getPluginDescriptor`.

**Comment by punya** [comment]
I solved my problem by making the dependency non-transitive, like so:

```
dependencies {
    compile "org.slf4j:slf4j-api:1.7.7"

    findbugsPlugins "jp.skypencil.findbugs.slf4j:findbugs-slf4j:1.2.4@jar"
}
```

... but this suggests that the POM should actually be fixed to omit the Guava dependency.

**Comment by KengoTODA** [comment]
Hi, could you give more information about `NullPointerException`? Why it happens when you omit `@jar`?

And I want to know why you think Guava dependency is the cause. Thanks for your cooperation!

**Comment by punya** [comment]
You can see the gradle file I used, and the full stack trace, at https://gist.github.com/punya/fbf7177370e5a5f98c6a2986926e4826.

I think that the Guava dependency is the cause because:
* The NPE I mentioned above appears to be on a line involving classloading
* The [jar](https://repo1.maven.org/maven2/jp/skypencil/findbugs/slf4j/bug-pattern/1.2.4/bug-pattern-1.2.4.jar) contains lots of Guava classes, but the [pom](https://repo1.maven.org/maven2/jp/skypencil/findbugs/slf4j/bug-pattern/1.2.4/bug-pattern-1.2.4.pom) still pulls in Guava as a transitive dependency, which could be confusing the classloader
* Removing the transitive dependency (by adding `@jar` or `transitive: false`) fixes the problem.
