### ISSUE TITLE
Pattern not working when using Checker Framework

### ISSUE THREAD

**Issue by maggu2810** [KengoTODA/findbugs-slf4j#50]
Hi,
I used your plugin for some time now. And first I would like to say: Thank you.

But now I have a problem:

Let's look at this code.

```java
        } catch (final FileNotFoundException ex) {
            logger().debug("File '{}' not found.", file, ex);
```

If I use your bug pattern with FindBugs all is fine (because there is no parameter for the exception).

Now I started to use the Checker Framework Nullness Checker.
Using it at the same run as your bug pattern extension I run into an error:

```text
[INFO] Count of placeholder(1) is not equal to count of parameter(2) [tmp.Test] At Test.java:[line 32] SLF4J_PLACE_HOLDER_MISMATCH
```

Perhaps it is related to the annotated JDK, but I don't know.

I created a very simple example, so you could reproduce this error (I used the code as similar as possible to the same in the project the error has been raised).
You can check out it here: https://github.com/maggu2810/findbugs-slf4j-pattern

* success: `mvn -Dfindbugs`
* failure: `mvn -Dfindbugs -Dcheckerframework=check`

Would be great if you could have a look at.

**Comment by KengoTODA** [comment]
Thanks for your share, I'll check.

**Comment by KengoTODA** [comment]
I cannot build your code, here is error message reported by maven:

```
Could not find artifact de.maggu2810.maven.build:resources:jar:1.7 in central (https://repo.maven.apache.org/maven2
```

**Comment by maggu2810** [comment]
Sorry about that, added the repo for that artifact using repositories... as it is used in a plugin dependency I need to add the repo to plugin repositories.
Should be fixed.

I tested it with an empty local maven repo. Should work now.

**Comment by KengoTODA** [comment]
@maggu2810 Thanks, I successfully build your code. And I found strange warning:

```
    [java] The following classes needed for analysis were missing:
     [java]   java.nio.charset.StandardCharsets
     [java]   java.io.FileNotFoundException
```

Problem is that, Findbugs cannot find `java.io.FileNotFoundException` so it's impossible to judge "`ex` is exception or not".

It seems that `org/checkerframework/jdk8/2.1.5/jdk8-2.1.5.jar` has no `java/io/FileNotFoundException.class` file nor `java/nio` directory. Do you know why? Is it OK?

**Comment by KengoTODA** [comment]
I think this is not plugin-specific problem, it's about difficulty of using Findbugs with Checker-framework.

**Comment by maggu2810** [comment]
> It seems that org/checkerframework/jdk8/2.1.5/jdk8-2.1.5.jar has no java/io/FileNotFoundException.class file nor java/nio directory.

It seems so.

> Do you know why?

Not really.

But as long as the maven compiler plugin is still able to compile the code, shouldn't FIndBugs work, too?

I need to read about the `-Xbootclasspath/p:...` parameter. Does it just add other stuff (that are preloaded) or does it really replace the JDK. For my current understanding the Checker Framework adds only annotated stuff, that is used in flavour of the other one. But if something is not found in the annotated packages the normal one is used.

I try to further investigate it.

**Comment by maggu2810** [comment]
FYI: For further investigation I added a profile to add the annotated JDK only.

You can use `mvn -Dfindbugs -Dannotated-jdk` to use FindBugs and the annotated JDK.
You are right, the usage of the annotated JDK results in the error.

```text
     [java] The following classes needed for analysis were missing:
     [java]   java.nio.charset.StandardCharsets
     [java]   java.io.FileNotFoundException
     [java] Warnings generated: 1
     [java] Missing classes: 2
```

**Comment by maggu2810** [comment]
FYI: For further investigation I added a profile to add the annotated JDK only.

You can use `mvn -Dfindbugs -Dannotated-jdk` to use FindBugs and the annotated JDK.
You are right, the usage of the annotated JDK results in the error.

```text
     [java] The following classes needed for analysis were missing:
     [java]   java.nio.charset.StandardCharsets
     [java]   java.io.FileNotFoundException
     [java] Warnings generated: 1
     [java] Missing classes: 2
```

---

I started a thread on the Checker Framework group:
https://groups.google.com/d/msg/checker-framework-discuss/H7pYgQR2qt8/sWM4BktCAwAJ

**Comment by maggu2810** [comment]
I will play a little bit more with my current setup, but it seems to be solved.
The failure is not about the boot classpath settings but about the added dependency (see linked thread above).
I changed the usage to not add the annotated JDK as a dependency (you could have a look at the last commit).
Okay for you to close?

**Comment by KengoTODA** [comment]
Yes, I'll close this. Please inform me freely when you face another. :)
