### ISSUE TITLE
Thoughts on transferring this to spotbugs org

### ISSUE THREAD

**Issue by hazendaz** [KengoTODA/findbugs-slf4j#502]
Given you are already part of spotbugs org and given there is a lot more contributors active over there, what would be your opinion of transferring this over.  Clearly it would be renamed to spotbugs-slf4j and 'bug-pattern' would be likely renamed too.  I'd like it to be a lot more configurable too.  I know you have the error prone variation and it suffers same too strict and sometimes incorrect per slf4j documentation (or should say that is very subjective).  So I know that might be odd to leave the one behind but maybe error prone might like that one if it gained same configuration.  Main thing for me is that I have all these defined all over and it seems like it should be found in one place.

Thoughts?

**Comment by KengoTODA** [comment]
For now I have no motivation to do so, but you may fork this repository into the spotbugs org if necessary.

**Comment by hazendaz** [comment]
ok no worries, I feel that would end up in us hard-forking and releasing separately which I'd prefer to avoid.  I do really want to use this plugin everywhere but understand its more complicated because two types exist and error prone probably would not want it and just because we do it would split its usage and not be very clean.  Closing ticket for now.  Thanks for responding back here as it will help discussion for us.
