### ISSUE TITLE
How to suppress warnings?

### ISSUE THREAD

**Issue by seanf** [KengoTODA/findbugs-slf4j#57]
Sorry if this is the wrong place to ask, but how do I suppress warnings when required?

I've tried putting these annotations on the offending method (one at a time):

    @SuppressFBWarnings("SLF4J_FORMAT_SHOULD_BE_CONST")
    @SuppressFBWarnings("SLF4J")
    @SuppressFBWarnings("CORRECTNESS")

But none of them seems to do anything.

**Comment by KengoTODA** [comment]
I believe that `@SuppressFBWarnings("SLF4J_FORMAT_SHOULD_BE_CONST")` should work.

**Comment by seanf** [comment]
Yes, it does. The exact same code. I must have forgotten to recompile or something. Thanks @KengoTODA !
