### ISSUE TITLE
Logger class name in anonymous class

### ISSUE THREAD

**Issue by svilenvul** [KengoTODA/findbugs-slf4j#61]
I have executed the `IllegalPassedClassDetector` on the Eclipse SmartHome project, and the following bug instance was reported: https://github.com/eclipse/smarthome/blob/bb6fee95637a84d632987bb5030cb8addfd9e7a2/bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/scheduler/ExpressionThreadPoolManager.java#L90

The message was: 
> Illegal class is passed to LoggerFactory#getLogger(Class). It should be one of [org.eclipse.smarthome.core.scheduler.ExpressionThreadPoolManager, org.eclipse.smarthome.core.scheduler.ExpressionThreadPoolManager$ExpressionThreadPoolExecutor, org.eclipse.smarthome.core.scheduler.ExpressionThreadPoolManager$ExpressionThreadPoolExecutor$2].

Could this be considered as unexpected behavior ?

**Comment by maggu2810** [comment]
@svilenvul This line of code create a anonymous subclass of `ThreadPoolExecutor.DiscardPolicy`. The anonymous class is part of the `ExpressionThreadPoolManager`.
A sub-class should not use the parent class as it logger class.

Or does it work in another example you could point me to?

**Comment by svilenvul** [comment]
@maggu2810, I agree with you. This is why I opened the issue in this repository and not in the Eclipse SmartHome. From my point of view this case should not be reported by the detector.

**Comment by svilenvul** [comment]
And one more question, could [this](https://github.com/eclipse/smarthome/blob/a7915ca737e2a657c8dd3fbe4e43ff37d875c1a9/bundles/io/org.eclipse.smarthome.io.rest.optimize/src/main/java/org/eclipse/smarthome/io/rest/optimize/internal/ResourceFilterImpl.java#L55) could be considered as false positive as well ?


> Illegal class is passed to LoggerFactory#getLogger(Class). It should be one of [org.eclipse.smarthome.io.rest.optimize.internal.ResourceFilterImpl].

**Comment by maggu2810** [comment]
For me using a parent class as class for a logger in a sub class is not valid. So I think it is okay to complain about.
