### ISSUE TITLE
SLF4J_PLACE_HOLDER_MISMATCH doesn't check Log.info(String) (without any parameters)

### ISSUE THREAD

**Issue by MateuszStefek** [KengoTODA/findbugs-slf4j#68]
`Logger.info("product: {}")` is not reported as a bug, while `Logger.info("product: {} value: {}", product)` is reported correctly.

This is probably because there's a separate method: `org.slf4j.Logger.info(String)`.

**Comment by KengoTODA** [comment]
We already have [a test case to cover this case](https://github.com/KengoTODA/findbugs-slf4j/blob/master/test-case/src/main/java/pkg/MessageOnly.java), and it doesn't report problem.

Could you provide .java file which can reproduce it? I guess this is related with lambda or something like it.
